# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: CI
on:
  push:
    branches: ["main", "v*"]
    # Also run on tag pushes, as the release.yml doesn't currently run tests
    tags: ["v*"]
    paths-ignore:
      - ".plugin-manifests/**"
      - "*.md"
      - "LICENSE"
  pull_request:
    branches: ["main", "v*"]
    paths-ignore:
      - ".plugin-manifests/**"
      - "*.md"
      - "LICENSE"

env:
  CARGO_TERM_COLOR: always
  RUST_VERSION: 1.74
jobs:
  lint-rust:
    name: Lint Rust
    runs-on: "ubuntu-latest"
    steps:
      # install dependencies
      - name: Install Rust toolchain
        run: |
          rustup toolchain install ${{ env.RUST_VERSION }} --component clippy --component rustfmt
          rustup default ${{ env.RUST_VERSION }}
      - name: Install Wasm Rust target
        run: rustup target add wasm32-wasi && rustup target add wasm32-unknown-unknown
      - name: Install cargo-component
        run: cargo install cargo-component
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "${{ runner.os }}-full-${{ hashFiles('./Cargo.lock') }}"

      - uses: actions/checkout@v4

      - name: Cargo Format
        run:
          cargo fmt --all -- --check

      - name: Cargo Clippy
        run:
          cargo clippy --workspace --all-targets --all-features -- -D warnings

  build-rust:
    name: Build Plugin
    runs-on: ${{ matrix.os }}
    needs: [lint-rust]
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      # install dependencies
      - name: Install latest Rust stable toolchain
        run: |
          rustup toolchain install ${{ env.RUST_VERSION }} --component clippy --component rustfmt
          rustup default ${{ env.RUST_VERSION }}
      - name: "Install Wasm Rust target"
        run: rustup target add wasm32-wasi && rustup target add wasm32-unknown-unknown
      - name: Install cargo-component
        run: cargo install cargo-component
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "${{ runner.os }}-full-${{ hashFiles('./Cargo.lock') }}"

      - uses: actions/checkout@v4

      - name: Cargo Build
        run: cargo build --release
        env:
          CARGO_INCREMENTAL: 0

  test-rust:
    name: Plugin Unit Tests
    runs-on: "ubuntu-latest"
    needs: [lint-rust]
    steps:
      - name: Install latest Rust stable toolchain
        run: |
          rustup toolchain install ${{ env.RUST_VERSION }} --component clippy --component rustfmt
          rustup default ${{ env.RUST_VERSION }}
      - name: "Install Wasm Rust target"
        run: rustup target add wasm32-wasi && rustup target add wasm32-unknown-unknown
      - name: Install cargo-component
        run: cargo install cargo-component
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "${{ runner.os }}-full-${{ hashFiles('./Cargo.lock') }}"

      - uses: actions/checkout@v4
      - name: Cargo Unit Tests
        run: cargo test --all --no-fail-fast -- --nocapture
        env:
          CARGO_INCREMENTAL: 0
          RUST_LOG: debug
